### ISSUE TITLE
XPath fail in Superfeedr.on_subscriptions

### ISSUE THREAD

**Issue by dodo** [superfeedr/superfeedr-ruby#2]
please fix the bug when superfeedr-ruby receives:
&lt;pubsub xmlns:superfeedr='http://superfeedr.com/xmpp-pubsub-ext' xmlns='http://jabber.org/protocol/pubsub'&gt;
 instead of &lt;pubsub&gt; (from spec)

to get this error just chance: spec/superfeedr_ruby_spec.rb
216|  describe "on_subscriptions" do
217|    it "should call the block with the page number and the list of feeds as an array" do
218|      xml = &lt;&lt;-EOXML
219|        &lt;iq type="result" to="you@superfeedr.com/home" id="subman1" from="firehoser.superfeedr.com"&gt;
221-           &lt;pubsub&gt;
221+          &lt;pubsub xmlns:superfeedr='http://superfeedr.com/xmpp-pubsub-ext' xmlns='http://jabber.org/protocol/pubsub'&gt;
222|             &lt;subscriptions page="3"&gt;

and to fix this bug change: lib/superfeedr.rb
138|  # Called with a response to a subscriptions listing
139|  def self.on_subscriptions(stanza, &block)
140-    page = stanza.xpath('//subscriptions').first["page"].to_i
140+   page = stanza.xpath('//&#42;[name()="subscriptions"]').first["page"].to_i
141-    feeds = stanza.xpath('//subscription').map { |s| CGI.unescapeHTML(s["node"]) }
141+    feeds = stanza.xpath('//&#42;[name()="subscriptions"]').map { |s| CGI.unescapeHTML(s["node"]) }
142|    block.call(page, feeds)
143|  end

(i hope this helps :p)

**Comment by astro** [comment]
http://github.com/superfeedr/superfeedr-ruby/commit/8630f8c85e03d92cff71980d71ccfbb03b9c07cb
