### ISSUE TITLE
no title in NotificationStanza

### ISSUE THREAD

**Issue by dodo** [superfeedr/superfeedr-ruby#3]
could you please add a method that provide the content of a message:event:status:title stanza in lib/stanzas/notification_stanza.rb.

**Comment by astro** [comment]
Fixed in http://github.com/superfeedr/superfeedr-ruby/commit/f97f54f3cb862935b75b0b12887414876863f467

**Comment by julien51** [comment]
Thanks Dodo for reporting the error... and thanks Stefan for fixing it!

**Comment by dodo** [comment]
no problem
