### ISSUE TITLE
It blows up when it tries to make another fetch request

### ISSUE THREAD

**Issue by millisami** [superfeedr/superfeedr-ruby#5]
I tried to use this example gist, but it blows out when it tries to fetch the feed.
This is the file and the error is below:
    require "rubygems"
    require "superfeedr"

```
## You can have all the XMPP logging by changing the Skates log level
Skates.logger.level = Log4r::INFO

Superfeedr.connect("jondoe@superfeedr.com", "secret") do 
  puts "Yay... connected ;)" 

  Superfeedr.on_notification do |notification|
    puts "The feed #{notification.feed_url} has been fetched (#{notification.http_status}: #{notification.message_status}) and will be fecthed again in #{(notification.next_fetch - Time.now)/60} minutes."
    notification.entries.each do |e|
      puts " - #{e.title} (#{e.link}) was published (#{e.published}) with #{e.unique_id} as unique id : \n #{e.summary} (#{e.chunk}/#{e.chunks})"
    end
  end

  Superfeedr.subscribe("http://github.com/superfeedr.atom") do |result|
    puts "Yay, subscribed to the github Atom feed for Superfeedr"  if result
    # Superfeedr.unsubscribe("http://github.com/superfeedr.atom") do |result|
    #   puts "Sad, you unsubscribed from the github Atom feed for Superfeedr" if result
    # end   
  end

  Superfeedr.subscribe("http://github.com/millisami.atom") do |result|
    puts "Subscribed to Millisami's github atom" if result
  end
  Superfeedr.subscribe("http://feeds.feedburner.com/NotifixiousFoundersBlog") do |result|
    puts "Subscribed to Notifixious' blog" if result
  end

  # Superfeedr.subscriptions(5) do |page, feeds|
  #   puts "On page #{page} : "
  #   puts feeds.inspect
  # end

end
```

The error is:

```
ree-1.8.7-2010.02 [~/codes/superfeedr-demo] ➔ ruby super-feedr.rb 
Yay... connected ;)
On page 5 : 
[]
Subscribed to Notifixious' blog
Yay, subscribed to the github Atom feed for Superfeedr
Subscribed to Millisami's github atom
ERROR : on_stanza failed : undefined method `parse' for Time:Class
/Users/millisami/.rvm/gems/ree-1.8.7-2010.02/gems/superfeedr-ruby-0.4.3/lib/stanzas/notification_stanza.rb:235:in `next_fetch'
super-feedr.rb:15
/Users/millisami/.rvm/gems/ree-1.8.7-2010.02/gems/superfeedr-ruby-0.4.3/lib/superfeedr.rb:200:in `call'
/Users/millisami/.rvm/gems/ree-1.8.7-2010.02/gems/superfeedr-ruby-0.4.3/lib/superfeedr.rb:200:in `on_stanza'
/Users/millisami/.rvm/gems/ree-1.8.7-2010.02/gems/skates-0.3.5/lib/skates/xmpp_connection.rb:140:in `receive_stanza'
/Users/millisami/.rvm/gems/ree-1.8.7-2010.02/gems/skates-0.3.5/lib/skates/client_connection.rb:110:in `receive_stanza'
/Users/millisami/.rvm/gems/ree-1.8.7-2010.02/gems/skates-0.3.5/lib/skates/xmpp_parser.rb:75:in `call'
/Users/millisami/.rvm/gems/ree-1.8.7-2010.02/gems/skates-0.3.5/lib/skates/xmpp_parser.rb:75:in `end_element'
/Users/millisami/.rvm/gems/ree-1.8.7-2010.02/gems/nokogiri-1.4.2/lib/nokogiri/xml/sax/document.rb:125:in `end_element_namespace'
/Users/millisami/.rvm/gems/ree-1.8.7-2010.02/gems/nokogiri-1.4.2/lib/nokogiri/xml/sax/push_parser.rb:47:in `native_write'
/Users/millisami/.rvm/gems/ree-1.8.7-2010.02/gems/nokogiri-1.4.2/lib/nokogiri/xml/sax/push_parser.rb:47:in `<<'
/Users/millisami/.rvm/gems/ree-1.8.7-2010.02/gems/skates-0.3.5/lib/skates/xmpp_parser.rb:28:in `push'
/Users/millisami/.rvm/gems/ree-1.8.7-2010.02/gems/skates-0.3.5/lib/skates/xmpp_connection.rb:187:in `receive_data'
/Users/millisami/.rvm/gems/ree-1.8.7-2010.02@global/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine'
/Users/millisami/.rvm/gems/ree-1.8.7-2010.02@global/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'
/Users/millisami/.rvm/gems/ree-1.8.7-2010.02/gems/superfeedr-ruby-0.4.3/lib/superfeedr.rb:52:in `connect'
super-feedr.rb:11
```

**Comment by julien51** [comment]
Try to add require 'time'. Some ruby versions are messing with this.

**Comment by millisami** [comment]
Well, after adding `require time`, this is the error:
    ree-1.8.7-2010.02 [~/codes/superfeedr-demo] ➔ ruby super-feedr.rb 
    ERROR : Skates::AuthenticationError
    /Users/millisami/.rvm/gems/ree-1.8.7-2010.02/gems/skates-0.3.5/lib/skates/client_connection.rb:152:in `receive_stanza'
    /Users/millisami/.rvm/gems/ree-1.8.7-2010.02/gems/skates-0.3.5/lib/skates/xmpp_parser.rb:75:in`call'
    /Users/millisami/.rvm/gems/ree-1.8.7-2010.02/gems/skates-0.3.5/lib/skates/xmpp_parser.rb:75:in `end_element'
    /Users/millisami/.rvm/gems/ree-1.8.7-2010.02/gems/nokogiri-1.4.2/lib/nokogiri/xml/sax/document.rb:125:in`end_element_namespace'
    /Users/millisami/.rvm/gems/ree-1.8.7-2010.02/gems/nokogiri-1.4.2/lib/nokogiri/xml/sax/push_parser.rb:47:in `native_write'
    /Users/millisami/.rvm/gems/ree-1.8.7-2010.02/gems/nokogiri-1.4.2/lib/nokogiri/xml/sax/push_parser.rb:47:in`<<'
    /Users/millisami/.rvm/gems/ree-1.8.7-2010.02/gems/skates-0.3.5/lib/skates/xmpp_parser.rb:28:in `push'
    /Users/millisami/.rvm/gems/ree-1.8.7-2010.02/gems/skates-0.3.5/lib/skates/xmpp_connection.rb:187:in`receive_data'
    /Users/millisami/.rvm/gems/ree-1.8.7-2010.02@global/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine'
    /Users/millisami/.rvm/gems/ree-1.8.7-2010.02@global/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`run'
    /Users/millisami/.rvm/gems/ree-1.8.7-2010.02/gems/superfeedr-ruby-0.4.3/lib/superfeedr.rb:52:in `connect'
    super-feedr.rb:8

**Comment by julien51** [comment]
I think that's pretty explicit! You're not using the right login/password.

Also, are you sure you wnat to use XMPP? I really feel that you're not an expreienced XMPP user. Please check this http://superfeedr.com/documentation#what_api

**Comment by millisami** [comment]
Yup, I'm new to XMPP.
But that was the code I found in your example code using ruby.
Is there any other example in ruby using the PubSubHubbub?

**Comment by julien51** [comment]
Millisami : PubSubHubbub is hard to build wrappers around, because it involves making calls and getting incoming calls. However it's also a _very_ simple protocol, so you can certainly get going very easily.
If you use Rails, check this : http://github.com/empika/Superfeedr-PubSubHubbub-Rails-Plugin

**Comment by millisami** [comment]
Thanks, I'll look into it.
